# One-time setup: local dev OUTSIDE Google Drive + archive folder ON Drive (MYDISK)
# Run from repo: .\scripts\setup-local-workspace.ps1

$ErrorActionPreference = 'Stop'

$repoHere = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$localDev = 'C:\Users\AM\Projects\Y\edecorus.ru'
$driveArchive = Join-Path $env:USERPROFILE 'MYDISK\Yodekor\edecorus'
$repoUrl = 'https://github.com/m11nic89co/edecorus.git'
$localConfig = Join-Path $PSScriptRoot 'workspace-paths.local.ps1'

Write-Host '=== edecorus: local workspace + Google Drive archive ===' -ForegroundColor Cyan

New-Item -ItemType Directory -Force -Path (Split-Path $localDev) | Out-Null
New-Item -ItemType Directory -Force -Path $driveArchive, (Join-Path $driveArchive 'site'), (Join-Path $driveArchive 'docs') | Out-Null

if (-not (Test-Path (Join-Path $localDev '.git'))) {
  Write-Host "Cloning to $localDev ..."
  git clone $repoUrl $localDev
} else {
  Write-Host "Pull latest in $localDev ..."
  git -C $localDev pull origin main
}

@(
  '# Auto-generated by setup-local-workspace.ps1'
  "`$LocalDevRoot = '$localDev'"
  "`$GoogleDriveRoot = '$driveArchive'"
) | Set-Content -Path $localConfig -Encoding UTF8

$localConfigDest = Join-Path $localDev 'scripts\workspace-paths.local.ps1'
New-Item -ItemType Directory -Force -Path (Split-Path $localConfigDest) | Out-Null
Copy-Item -Path $localConfig -Destination $localConfigDest -Force

Write-Host "Created $localConfig" -ForegroundColor Green
Write-Host "Drive archive: $driveArchive" -ForegroundColor Green
Write-Host ""
Write-Host "Next:" -ForegroundColor Yellow
Write-Host "  1. Cursor: File -> Open Folder -> $localDev"
Write-Host "  2. After edits: .\scripts\sync-to-google-drive.ps1  (from $localDev)"
Write-Host "  3. Deploy: git push (GitHub Pages)"

& (Join-Path $localDev 'scripts\sync-to-google-drive.ps1')
